name: Docs

on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set Toolchain
      run: rustup default nightly    
    - name: Update
      run: rustup update    
    - name: Build doc
      run: RUSTDOCFLAGS="--html-in-header katex.html" cargo doc --document-private-items --no-deps
    - name: Set Index
      run: echo '<meta http-equiv=refresh content=0;url=air_flow/index.html>' > target/doc/index.html
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: target/doc/ # The folder the action should deploy.
  
